In [3]:
import numpy as np
import pandas as pd
from scipy import stats

In [4]:
covid_data = pd.read_csv('covid_data.csv')
covid_data=covid_data[['Entity','Code','Day','Central estimate']]

In [5]:
covid_data.head(5)

        Entity Code         Day  Central estimate
0  Afghanistan  AFG  2024-06-17         422.11630
1      Albania  ALB  2024-06-17         550.91364
2      Algeria  DZA  2024-06-17         294.52670
3      Andorra  AND  2024-06-17         223.76707
4       Angola  AGO  2024-06-17         149.25598

In [6]:
covid_data.dtypes

Entity                  str
Code                    str
Day                     str
Central estimate    float64
dtype: object

In [7]:
covid_data.describe()

       Central estimate
count        200.000000
mean         294.708416
std          203.432966
min         -286.298000
25%          172.814098
50%          251.662325
75%          392.089495
max         1096.093000

In [8]:
covid_data.shape

(200, 4)

In [9]:
data_mean=np.mean(covid_data['Central estimate'])
data_median=np.median(covid_data['Central estimate'])
data_mode=stats.mode(covid_data['Central estimate'])
data_variance=np.var(covid_data['Central estimate'])
data_sd=np.std(covid_data['Central estimate'])
data_max=np.max(covid_data['Central estimate'])
data_min=np.min(covid_data['Central estimate'])
data_percentiles=np.percentile(covid_data['Central estimate'],60)
data_quartiles=np.percentile(covid_data['Central estimate'],0.75)
data_IQR=stats.iqr(covid_data['Central estimate'])

In [10]:
print(f'Mean: {data_mean}')
print(f'Median: {data_median}')
print(f'Mode: {data_mode}')
print(f'Variance: {data_variance}')
print(f'Std Dev: {data_sd}')
print(f'Max: {data_max}')
print(f'Min: {data_min}')
print(f'60th Percentile: {data_percentiles}')
print(f'75th Percentile: {data_quartiles}')
print(f'IQR: {data_IQR}')

Mean: 294.7084163715
Median: 251.662325
Mode: ModeResult(mode=np.float64(-286.298), count=np.int64(1))
Variance: 41178.04664093703
Std Dev: 202.92374587745277
Max: 1096.093
Min: -286.298
60th Percentile: 303.793724
75th Percentile: -101.63593845
IQR: 219.27539749999997